### ISSUE TITLE
Custom datasets and camera extrinsics.

### ISSUE THREAD

**Issue by Chester-CS** [jchibane/srf#10]
Hello jchibane, I'm wondering whether your code can be applied to other datasets such as ShapeNet and custom blender datasets.
How did you get the raw pose_extrinsics for the DTU dataset ?
![image](https://user-images.githubusercontent.com/52237697/129302627-0bfac3bb-fa86-4b70-bd3a-92e90407200c.png)
Thanks.

**Comment by jchibane** [comment]
Hey,
these camera intrinsics are somewhat buried in the DTU dataset, but yes they are there. We did not estimate those ourselves.
We did not apply the code on other datasets, but if you adopt the dataset classes correctly, this should be possible!
Best,
Julian
