### ISSUE TITLE
Failed to compile torchsearchsorted

### ISSUE THREAD

**Issue by yizhou-wang** [jchibane/srf#2]
Thanks for this valuable work! 

I failed to run `pip install torchsearchsorted/`. I have Ubuntu 18.04 + GCC v8.4 + CUDA 10.1 + python 3.6.12 + pytorch 1.6. 
But on another Ubuntu 16.04 (GCC 5.4) machine, it can be compiled successfully. 

Is that an error due to any package version issues? Could you please help? Thanks!

Here I show one of the error messages (more detailed error messages can be provided upon request): 

```
    ninja: build stopped: subcommand failed.       
  Traceback (most recent call last):                    
    File "/home/t-yizhouwang/anaconda3/envs/srf/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1515, in _run_ninja_build 
      env=env)                                                                    
    File "/home/t-yizhouwang/anaconda3/envs/srf/lib/python3.6/subprocess.py", line 438, in run
      output=stdout, stderr=stderr)  
  subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1. 
```

**Comment by yizhou-wang** [comment]
I'm thinking if the correct version for GCC should be 5.4?

**Comment by jchibane** [comment]
Hi @yizhou-wang ,

yes, I think the library is sensitive to correct version numbers of GCC and it might be that 

> Ubuntu 16.04 (GCC 5.4) 

is outdated.
However, I'm not the writer or the library - please check 
https://github.com/aliutkus/torchsearchsorted
and have a look into issues or post a novel one!

Best,
Julian

**Comment by jchibane** [comment]
I removed the dependency altogether - you can do a git pull and rebuild the srf environment following the readme.
