### ISSUE TITLE
Obtaining 3D mesh as in Fig6

### ISSUE THREAD

**Issue by november07** [jchibane/srf#3]
Hi, I was hoping to obtain the 3D mesh as shown in Figure 6. I assume you'd follow the steps to threshold the density predictions and run Marching cubes on a dense grid of points. Could you perhaps provide the exact detail? or upload the code to obtain the paper's Figure6 mesh output? 

thanks,

**Comment by jchibane** [comment]
Hey @november07 ,
I just added the 3D reconstruction code.
Best,
Julian
