### ISSUE TITLE
Memory leak during inference

### ISSUE THREAD

**Issue by chris-nbi** [jchibane/srf#4]
Hi, I am attempting for novel view synthesis by running the pretrained inference with the provided command and code.
Even if I reduce the number of ray samples, the memory was exploding (500G memory + a lot of swap on the machine). Does anybody else experience this? or could the author kindly comment on this?

**Comment by yizhou-wang** [comment]
Yes, I also noticed that. But, it can work with `--render_factor 8`, which results in a much lower rendering resolution.

**Comment by jchibane** [comment]
Hey all,
with the current version (please do a git pull, and update the srf environment), it should take around 130GB.
Best,
Julian
