### ISSUE TITLE
split.pkl was removed from the GitHub repository

### ISSUE THREAD

**Issue by yizhou-wang** [jchibane/srf#5]
Based on the latest version, I got this error: 
```FileNotFoundError: [Errno 2] No such file or directory: './data/DTU_MVS//split.pkl' ```

I tried to copy the original `split_shuffle.pkl` to that location and it works. I guess you should not remove that file?

**Comment by jchibane** [comment]
Thanks a lot for notifying!
I just uploaded the missing file.
Best,
Julian

**Comment by yizhou-wang** [comment]
Sorry, but I think this file is missing again in the current version.

**Comment by jchibane** [comment]
Thanks for reporting again. Should be solved and fixed also in the future now!
