### ISSUE TITLE
Pre-trained ckpt files are out of date

### ISSUE THREAD

**Issue by yizhou-wang** [jchibane/srf#7]
When I run inference using the latest code, I got this error:
`KeyError: 'sim_combinations'` at
https://github.com/jchibane/srf/blob/ce97b2797578a96818c2b53b3a38d34218d2f55f/model.py#L213

I guess the pre-trained ckpt files are out of date without this key included? (Comment this line out will work for inference.) Thanks!

**Comment by jchibane** [comment]
Thanks for reporting, this is fixed in the current version!
